"""create users & passwords in schema data

Revision ID: 4eaf8797564a
Revises: 
Create Date: 2022-12-18 14:48:47.660493

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4eaf8797564a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('mail', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('patronymic', sa.String(), nullable=True),
        sa.Column('login', sa.String(), nullable=True),
        sa.Column('telephone', sa.String(), nullable=True),
        sa.Column('region', sa.String(), nullable=True),
        sa.Column('last_visit', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('login'),
        sa.UniqueConstraint('mail'),
        sa.UniqueConstraint('telephone'),
        schema='data',
    )
    op.create_index(op.f('ix_data_users_id'), 'users', ['id'], unique=False, schema='data')
    op.create_table(
        'users_passwords',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('password', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['id'], ['data.users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='data',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_passwords', schema='data')
    op.drop_index(op.f('ix_data_users_id'), table_name='users', schema='data')
    op.drop_table('users', schema='data')
    # ### end Alembic commands ###
